theme: jekyll-theme-cayman
<!DOCTYPE html>
<html>
<head>
<title>Muhammad Arasyi - Curriculum Vitae</title>

<meta name="viewport" content="width=device-width"/>
<meta name="description" content="The Curriculum Vitae of Joe Bloggs."/>
<meta charset="UTF-8"> 

<link type="text/css" rel="stylesheet" href="style.css">
<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>

</head>
<body id="top">
<div id="cv" class="instaFade">
    <div class="mainDetails">
        <div id="headshot" class="quickFade">
            <img src="Kucing.jpg" alt="Muhammad Arasyi" />
        </div>
        
        <div id="name">
            <h1 class="quickFade delayTwo">Curriculum Vitae</h1>
            <h2 class="quickFade delayThree">Muhammad Arasyi</h2>
        </div>
        
        <div id="contactDetails" class="quickFade delayFour">
        <table>
            <tr>
                <td>E-mail</td><td>:</td><td><a href="mailto:Arasyiayas11@gmail.com" target="_blank">Arasyiayas11@gmail.com</a></td>
            </tr>
            <tr>
                <td>Facebook</td><td>:</td><td> <a href="http://www.facebook.com/Muhammad Arasyi"> www.facebook.com/Muhammad Arasyi</a></td>
            </tr>
            <tr>
                <td>Mobile</td><td>:</td><td> 085270023491</td>
            </tr>
        </table>
        </div>
        <div class="clear"></div>
    </div>
    
    <div id="mainArea" class="quickFade delayFive">
        <section>
            <article>
                <div class="sectionTitle">
                    <h1>Tujuan Karir</h1>
                </div>
                
                <div class="sectionContent">
                    <p>Sebagai seorang Lulusan di bidang Teknik Informatika,Saya berkeinginan untuk mengembangkan dan menambah kemampuan di berbagai bidang lain,
                    Salah satunya adalah di bidang Perbankan.
                    Saya berambisi untuk terus mencari pengalaman sebanyak mungkin untuk menambah kualitas diri saya. 
                   
                    </p>
                </div>
            </article>
            <div class="clear"></div>
        </section>
        
        
        <section>
            <div class="sectionTitle">
                <h1>Data Pribadi</h1>
            </div>
            
            <div class="sectionContent">
                <table>
                <tr>
                    <td>Nama</td><td>: Muhammad Arasyi</td>
                </tr>
                <tr>
                    <td>Tempat, Tanggal Lahir</td><td>: Langsa, 11 Oktober 1999</td>
                </tr>
                <tr>
                    <td>Agama</td><td>: Islam</td>
                </tr>
                <tr>
                    <td>Warga Negara</td><td>: Indonesia</td>
                </tr>
                <tr>
                    <td>Alamat</td><td>: Lhoksukon</td>
                </tr>
                <tr>
                    <td>E-mail</td><td>: Muhammad Arasyi@gmail.com</td>
                </tr>
                </table>
                
            </div>
            <div class="clear"></div>
        </section>
        
        
        <section>
            <div class="sectionTitle">
                <h1>Keahlian</h1>
            </div>
            
            <div class="sectionContent">
                <table width=500px>
                <tr>
                    <td>HTML</td><td>Software</td><td>Microsoft Office</td>
                </tr>
                <tr>
                    <td>PHP</td><td>Network Configuration</td><td>Hardware Repairing</td>
                </tr>
                <tr>
                    <td>LAN</td><td>Basic Database</td><td>Photoshop</td>
                </tr>
                </table><br>
            </div>
            <div class="clear"></div>
        </section>
        
        
        <section>
            <div class="sectionTitle">
                <h1>Riwayat Pendidikan</h1>
            </div>
            
            <div class="sectionContent">
                <article>
                    <h2>Formal</h2><br>
                    <h4>MIN Lhoksukon</h4>
                    <p class="subDetails">2005-2011<p>
                    
                </article>
                
                <article>
                    <h4>MTSs Al-Muslimun</h4>
                    <p class="subDetails">2011-2014</p>
                    
                </article>
                <article>
                    <h4>MAS Al-Muslimun</h4>
                    <p class="subDetails">2014-2017</p>
                </article><br>
                <article>
                    <h2>Non-Formal</h2><br>
                    <h4>Tekin Informatika Universitas Malikussaleh</h4>
                    <p class="subDetails">2017-...</p>
            </div>
            <div class="clear"></div>
        </section><br><br>
        <section>
            <div>
            <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Demikian Curriculum Vitae ini saya buat dengan Sebenar benarnya,Untuk dapat dipergunakan sebagai mana mestinya.</p>
            <br><br><br><br><br><br>
            <p align="right">Hormat Saya,<br><br><br>Muhammad Arasyi</p>
        </section>
        
    </div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3753241-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
</body>
</html>
